name: productionai
channels:
  - conda-forge
dependencies:
  # python 3.13 currently has an issue with lxml
  - python==3.12
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - simpy
  - pygad
  # dependencies of basyx-python-sdk
  - pip
  - lxml~=4.9.4
  - pip:
    - basyx-python-sdk
  
